spring.application.name=gateway

server.port=8080

spring.threads.virtual.enabled=true

#gateway
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://user-service:8081
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081/
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0].name=authenticationFilter
spring.cloud.gateway.server.webmvc.routes[0].filters[0].args.role=USER

spring.cloud.gateway.server.webmvc.routes[3].id=storage-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://storage-service:8086
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/storage/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0].name=authenticationFilter
spring.cloud.gateway.server.webmvc.routes[3].filters[0].args.role=USER

spring.cloud.gateway.server.webmvc.routes[5].id=media-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://media-service:8088
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/media/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0].name=authenticationFilter
spring.cloud.gateway.server.webmvc.routes[5].filters[0].args.role=ADMIN

spring.cloud.gateway.server.webmvc.routes[6].id=main-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://main-service:8087
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/process/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0].name=authenticationFilter
spring.cloud.gateway.server.webmvc.routes[6].filters[0].args.role=ADMIN


spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://auth-service:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[2].id=eureka
spring.cloud.gateway.server.webmvc.routes[2].uri=${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/eureka/main
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=SetPath=/

spring.cloud.gateway.server.webmvc.routes[4].id=eureka-static
spring.cloud.gateway.server.webmvc.routes[4].uri=${EUREKA_CLIENT_DEFAULT_ZONE:http://localhost:8761}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/eureka/**

#jwt
jwt.secret.key=q2874q72n6q87xnd6q8d683ged8g3e32edgwd

#default values for rabbit mq
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

rabbitmq.exchange.progress=progress.events.exchange
rabbitmq.queue.progress=gateway.progress.queue
rabbitmq.queue.progress.routingKey=progress.*

# STOMP Broker Relay (WebSocket relay)
websocket.relay.host=${RABBIT_WEBSOCKET_HOST:localhost}
websocket.relay.port=${RABBIT_WEBSOCKET_PORT:61613}
websocket.relay.username=${RABBIT_WEBSOCKET_USER:guest}
websocket.relay.password=${RABBIT_WEBSOCKET_PASS:guest}

#cors
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Optional: Add to simple URL handler mapping for requests not handled by a specific route predicate
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true


management.tracing.sampling.probability=${OTEL_TRACE_SAMPLING_PROB:1.0}
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_TRACE_ENDPOINT:http://localhost:4318/v1/traces}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_LOGS_ENDPOINT:http://localhost:4318/v1/logs}
management.otlp.metrics.export.url=${OTEL_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}
